/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Excel */
        post: operations["import_excel_api_v1_import_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Status */
        get: operations["import_status_api_v1_import__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/sap-rfc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Sap Rfc */
        post: operations["import_sap_rfc_api_v1_import_sap_rfc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/node/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_v1_graph_node__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/impact/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impact */
        get: operations["impact_api_v1_impact__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AffectedGroup
         * @description Affected items grouped by node type.
         */
        AffectedGroup: {
            label: components["schemas"]["NodeLabel"];
            /** Items */
            items: components["schemas"]["AffectedItem"][];
            /** Count */
            count: number;
        };
        /** AffectedItem */
        AffectedItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            label: components["schemas"]["NodeLabel"];
            /** Hop Distance */
            hop_distance: number;
            confidence: components["schemas"]["ConfidenceEnum"];
        };
        /** Body_import_excel_api_v1_import_excel_post */
        Body_import_excel_api_v1_import_excel_post: {
            /** File */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Text */
            text: string;
            /** Highlighted Node Ids */
            highlighted_node_ids: string[];
        };
        /**
         * ConfidenceEnum
         * @enum {string}
         */
        ConfidenceEnum: "direct" | "inferred";
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeSchema"][];
            /** Relationships */
            relationships: components["schemas"]["RelationshipSchema"][];
            /** Returned Count */
            returned_count: number;
            /** Total Count */
            total_count: number;
            /** Limit */
            limit: number;
            /** Truncated */
            truncated: boolean;
            /** Truncation Warning */
            truncation_warning?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            neo4j: components["schemas"]["Neo4jStatus"];
        };
        /** ImpactResponse */
        ImpactResponse: {
            /** Node Id */
            node_id: string;
            /** Risk Score */
            risk_score: number;
            /** Total Affected */
            total_affected: number;
            /** Affected Groups */
            affected_groups: components["schemas"]["AffectedGroup"][];
            /** Explanation */
            explanation: string;
        };
        /**
         * ImportJobResponse
         * @description Returned when an import job is accepted.
         */
        ImportJobResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["ImportStage"];
        };
        /**
         * ImportStage
         * @description Staged status of an import job.
         *
         *     Shaped like a real queue's status contract (see CLAUDE.md) so the in-memory
         *     implementation can be swapped later without touching the frontend.
         * @enum {string}
         */
        ImportStage: "queued" | "parsing" | "inferring" | "writing" | "complete" | "failed";
        /**
         * JobStatusResponse
         * @description Progress of an import job, polled by the frontend.
         */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["ImportStage"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /** Neo4jStatus */
        Neo4jStatus: {
            /** Connected */
            connected: boolean;
        };
        /** NodeDetailResponse */
        NodeDetailResponse: {
            node: components["schemas"]["NodeSchema"];
            /** Neighbors */
            neighbors: components["schemas"]["NodeSchema"][];
            /** Relationships */
            relationships: components["schemas"]["RelationshipSchema"][];
        };
        /**
         * NodeLabel
         * @enum {string}
         */
        NodeLabel: "Program" | "Table" | "FunctionModule" | "BAdI" | "Job" | "Transport" | "User";
        /** NodeSchema */
        NodeSchema: {
            /** Id */
            id: string;
            label: components["schemas"]["NodeLabel"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Business Meaning */
            business_meaning: string;
            source: components["schemas"]["SourceEnum"];
            confidence: components["schemas"]["ConfidenceEnum"];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
            /** Visibility */
            visibility?: string | null;
        };
        /** RelationshipSchema */
        RelationshipSchema: {
            /** Id */
            id: string;
            type: components["schemas"]["RelationshipType"];
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            source: components["schemas"]["SourceEnum"];
            confidence: components["schemas"]["ConfidenceEnum"];
            /** Derived From */
            derived_from: string;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /**
         * RelationshipType
         * @enum {string}
         */
        RelationshipType: "READS" | "WRITES" | "CALLS" | "IMPLEMENTS" | "EXECUTES" | "CHANGED" | "CREATED";
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
            /** Count */
            count: number;
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            label: components["schemas"]["NodeLabel"];
            /** Description */
            description: string;
            /** Score */
            score: number;
        };
        /**
         * SourceEnum
         * @description Provenance of a node/relationship.
         * @enum {string}
         */
        SourceEnum: "excel_import" | "inferred" | "sap_rfc";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_excel_api_v1_import_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_excel_api_v1_import_excel_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_status_api_v1_import__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sap_rfc_api_v1_import_sap_rfc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobResponse"];
                };
            };
        };
    };
    get_graph_api_v1_graph_get: {
        parameters: {
            query?: {
                /** @description Max nodes to return (capped at the server maximum). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_api_v1_graph_node__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    impact_api_v1_impact__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
