"""Unit tests for the impact-analysis service (GRAPH-D3.1).

The expected blast radius is transcribed verbatim from docs/flagship-blast-radius.md
(NOT generated by running the service). The input graph is the real flagship
dataset, parsed from demo-data/flagship.xlsx via the Excel importer (no Neo4j).
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

from adapters.importer_excel import ExcelImporter
from domain.graph_ports import GraphRepository
from domain.services.impact_analysis import ImpactAnalysisService

FLAGSHIP_XLSX = Path(__file__).resolve().parents[4] / "demo-data" / "flagship.xlsx"

# Transcribed from docs/flagship-blast-radius.md — Z_PRICE_ENGINE blast radius.
# (node id, hop distance, confidence)
EXPECTED_RADIUS: set[tuple[str, int, str]] = {
    ("ZBADI_PRICE_OVERRIDE", 1, "direct"),
    ("Z_FM_CURRENCY_CONVERT", 1, "direct"),
    ("Z_FM_TAX_LOOKUP", 1, "direct"),
    ("Z_FM_VALIDATE_PRICE", 1, "direct"),
    ("ZJOB_MONTH_END_CLOSE", 1, "direct"),
    ("ZJOB_NIGHTLY_PRICING", 1, "direct"),
    ("ZTABLE_PRICE_AUDIT", 1, "direct"),
    ("ZTABLE_PRICE_LOG", 1, "direct"),
    ("ZTABLE_VALIDATION_ERRORS", 1, "inferred"),
    ("Z_REPORT_COMPLIANCE", 2, "direct"),
    ("Z_REPORT_MARGIN", 2, "direct"),
    ("ZJOB_QUARTERLY_AUDIT", 3, "direct"),
    ("ZJOB_WEEKLY_REPORTING", 3, "direct"),
}

EXPECTED_SCORE = 74  # documented formula; see impact_analysis module docstring


class _FlagshipRepo(GraphRepository):
    """A GraphRepository whose get_graph returns the parsed flagship dataset."""

    def __init__(self) -> None:
        result = ExcelImporter().parse(FLAGSHIP_XLSX.read_bytes())
        self._nodes = [
            {"id": n.name, "label": n.__class__.__name__} for n in result.nodes
        ]
        self._rels = [
            {
                "source_id": r.source_name,
                "target_id": r.target_name,
                "type": r.type.value,
                "confidence": r.confidence.value,
            }
            for r in result.relationships
        ]

    def get_graph(self, limit: int) -> dict[str, Any]:
        return {
            "nodes": self._nodes,
            "relationships": self._rels,
            "total_count": len(self._nodes),
        }

    # Unused by the impact service.
    def health_check(self) -> bool:
        raise NotImplementedError

    def write_nodes(self, nodes: Sequence[Any]) -> None:
        raise NotImplementedError

    def write_relationships(self, relationships: Sequence[Any]) -> None:
        raise NotImplementedError

    def get_node(self, node_id: str) -> Any:
        raise NotImplementedError

    def search(self, query: str, limit: int) -> list[dict[str, Any]]:
        raise NotImplementedError


# Parse the workbook once (openpyxl load is the slow part).
_REPO = _FlagshipRepo()


def test_flagship_blast_radius_matches_doc_exactly():
    service = ImpactAnalysisService(_REPO)
    result = service.analyze("Z_PRICE_ENGINE")

    actual = {
        (node.id, node.hop_distance, node.confidence.value) for node in result.affected
    }
    assert actual == EXPECTED_RADIUS
    assert len(result.affected) == 13


def test_sparse_node_has_empty_radius_and_zero_score():
    service = ImpactAnalysisService(_REPO)
    result = service.analyze("Z_LEGACY_REBATE_CALC")

    assert result.affected == []
    assert result.risk_score == 0


def test_risk_score_is_deterministic_and_documented():
    service = ImpactAnalysisService(_REPO)
    a = service.analyze("Z_PRICE_ENGINE").risk_score
    b = service.analyze("Z_PRICE_ENGINE").risk_score

    assert a == b  # deterministic across runs
    assert a == EXPECTED_SCORE  # matches the documented formula
    assert 60 <= a <= 85  # serious but not fake
